name: ESLint
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
jobs:
  eslint:
    strategy:
      matrix:
        node_version:
          - 10.x
          - 12.x
    runs-on: ubuntu-latest
    steps:
      - name: SCM
        uses: actions/checkout@v1
      - name: node ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}
      - run: npm install
      - run: npm run eslint
      - run: npm run build
